#! /usr/bin/python3
import tornado.ioloop
import tornado.web
import pandas as pd

class MainHandler(tornado.web.RequestHandler):
    def get(self):
        self.write("Hello, world")
    def post(self):
        ReceiveNewMarket(self.get_argument("stock"))

class WebSocketHandler(tornado.websocket.WebSocketHandler):
    cols = ["id","user","request"]
    web_socket_request = DataFrame(columns = cols) 
    def open(self):
        WebSocketHandler.user.add([self,message])

    def on_message(self,message):
        pass

    def on_close(self):
        WebSocketHandler.user.remove(self)

    def check_origin(self,origin):
        return True

def make_app():
    return tornado.web.Application([
    (r'/', MainHandler),
    (r'/ws',WebSocketHandler),
    ])

if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
